name: pgai 
services:
 db:
   image: timescale/timescaledb-ha:pg17
   environment:
     POSTGRES_PASSWORD: postgres
   ports:
     - "5432:5432"
   volumes:
     - ./data:/var/lib/postgresql/data
 vectorizer-worker:
   image: timescale/pgai-vectorizer-worker
   environment:
     PGAI_VECTORIZER_WORKER_DB_URL: postgres://postgres:postgres@db:5432/postgres
     OLLAMA_HOST: http://ollama:11434
   command: [ "--poll-interval", "10s" ]
 ollama:
   build:
     context: ./ollama
     dockerfile: Dockerfile
   volumes:
     - ./ollama_data/ollama:/root/.ollama
   deploy:
     resources:
       reservations:
         devices:
           - driver: nvidia
             count: 1
             capabilities: [gpu]